"""Parameter manifest: UI metadata for every editable contract field.

Frozen in M2 so parallel agents cannot diverge on ranges, scales, steps, or
display units. Values are SI; ``display_factor`` converts SI → display unit
(``value_display = value_si * display_factor``).

Mode-dependent operating values are separate entries with a ``mode`` field;
their defaults are UI seeds derived from the paper operating point (they do
not alter the scientific defaults in :mod:`microtubes_core.defaults`).
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from microtubes_core.contracts import LinkGroup
from microtubes_core.defaults import CAPILLARY_CONSTANT_AL

MANIFEST_VERSION = "1.0.0"


class ParameterSpec(BaseModel):
    model_config = ConfigDict(extra="forbid")

    path: str = Field(description="Contract path relative to CoolerConfiguration or request")
    group: str = Field(description="Link group or 'sweep'")
    label: str
    unit: str = Field(description="SI unit of the contract value")
    display_unit: str
    display_factor: float = Field(description="value_display = value_si * display_factor")
    minimum: float = Field(description="SI")
    maximum: float = Field(description="SI")
    default: float = Field(description="SI")
    scale: Literal["log", "linear"]
    step_display: float | None = Field(
        default=None, description="Display-unit step for numeric entry; None = continuous"
    )
    integer: bool = False
    mode: str | None = Field(
        default=None, description="Operating mode this value entry belongs to (if any)"
    )
    description: str = ""


def _p(
    path: str,
    group: LinkGroup | str,
    label: str,
    unit: str,
    display_unit: str,
    display_factor: float,
    minimum: float,
    maximum: float,
    default: float,
    scale: Literal["log", "linear"],
    *,
    step_display: float | None = None,
    integer: bool = False,
    mode: str | None = None,
    description: str = "",
) -> ParameterSpec:
    return ParameterSpec(
        path=path,
        group=group.value if isinstance(group, LinkGroup) else group,
        label=label,
        unit=unit,
        display_unit=display_unit,
        display_factor=display_factor,
        minimum=minimum,
        maximum=maximum,
        default=default,
        scale=scale,
        step_display=step_display,
        integer=integer,
        mode=mode,
        description=description,
    )


def build_manifest() -> list[ParameterSpec]:
    g = LinkGroup.geometry
    m = LinkGroup.materials
    a = LinkGroup.air_side
    c = LinkGroup.coolant_side
    b = LinkGroup.boundary_conditions

    return [
        # --- geometry (canonical dimensions) --------------------------------
        _p(
            "geometry.dimensions.width",
            g,
            "Package width (transverse)",
            "m",
            "mm",
            1e3,
            0.01,
            1.0,
            0.0984,
            "log",
            description="Extent transverse to the air flow",
        ),
        _p(
            "geometry.dimensions.depth",
            g,
            "Package depth (air-flow direction)",
            "m",
            "mm",
            1e3,
            0.01,
            1.0,
            0.072,
            "log",
        ),
        _p(
            "geometry.dimensions.tube_length",
            g,
            "Tube length L",
            "m",
            "mm",
            1e3,
            0.02,
            2.0,
            0.160,
            "log",
        ),
        # --- geometry (volume/aspect representation) ------------------------
        _p(
            "geometry.volume_aspect.volume",
            g,
            "Package volume",
            "m^3",
            "L",
            1e3,
            1e-5,
            0.1,
            0.0984 * 0.072 * 0.160,
            "log",
        ),
        _p(
            "geometry.volume_aspect.aspect_width_over_depth",
            g,
            "Aspect ratio width/depth",
            "-",
            "-",
            1.0,
            0.1,
            10.0,
            0.0984 / 0.072,
            "log",
        ),
        _p(
            "geometry.volume_aspect.aspect_length_over_depth",
            g,
            "Aspect ratio length/depth",
            "-",
            "-",
            1.0,
            0.1,
            10.0,
            0.160 / 0.072,
            "log",
        ),
        _p(
            "geometry.pitch_transverse_ratio",
            g,
            "Transverse pitch ratio a = S_T/d_o",
            "-",
            "-",
            1.0,
            1.01,
            10.0,
            3.28,
            "log",
            description="a ≤ 1 would overlap tubes; model uses inline bank",
        ),
        _p(
            "geometry.pitch_longitudinal_ratio",
            g,
            "Longitudinal pitch ratio b = S_L/d_o",
            "-",
            "-",
            1.0,
            1.01,
            10.0,
            2.00,
            "log",
        ),
        # --- design point (KPI evaluation, linked with geometry) ------------
        _p(
            "design_point.outer_diameter",
            g,
            "KPI design point d_o",
            "m",
            "mm",
            1e3,
            0.1e-3,
            10e-3,
            1.0e-3,
            "log",
        ),
        _p(
            "design_point.wall_thickness",
            g,
            "KPI design point wall t",
            "m",
            "mm",
            1e3,
            0.001e-3,
            4.5e-3,
            0.1e-3,
            "log",
        ),
        # --- material --------------------------------------------------------
        _p(
            "material.thermal_conductivity",
            m,
            "Thermal conductivity λ",
            "W/(m K)",
            "W/(m K)",
            1.0,
            0.05,
            500.0,
            220.0,
            "log",
        ),
        _p(
            "material.tensile_strength",
            m,
            "Tensile strength Rm",
            "Pa",
            "MPa",
            1e-6,
            1e6,
            1e9,
            200e6,
            "log",
        ),
        _p(
            "material.min_wall_thickness",
            m,
            "Technology minimum wall",
            "m",
            "mm",
            1e3,
            1e-6,
            5e-4,
            0.07e-3,
            "log",
        ),
        _p(
            "material.capillary_constant",
            m,
            "Capillary constant C_cap",
            "m^2",
            "mm^2",
            1e6,
            1e-7,
            5e-5,
            CAPILLARY_CONSTANT_AL,
            "log",
            description="Full-gap slit convention h = C_cap/(s·G)",
        ),
        _p(
            "material.cost_reference_index",
            m,
            "Cost reference index",
            "-",
            "-",
            1.0,
            0.01,
            100.0,
            2.096225695575453,
            "log",
        ),
        # --- air side ---------------------------------------------------------
        _p(
            "air_side.fluid.density",
            a,
            "Air density ρ",
            "kg/m^3",
            "kg/m^3",
            1.0,
            0.1,
            1500.0,
            1.189,
            "log",
        ),
        _p(
            "air_side.fluid.specific_heat_capacity",
            a,
            "Air cp",
            "J/(kg K)",
            "J/(kg K)",
            1.0,
            100.0,
            10000.0,
            1006.0,
            "log",
        ),
        _p(
            "air_side.fluid.thermal_conductivity",
            a,
            "Air λ",
            "W/(m K)",
            "W/(m K)",
            1.0,
            0.005,
            1.0,
            0.02587,
            "log",
        ),
        _p(
            "air_side.fluid.kinematic_viscosity",
            a,
            "Air ν",
            "m^2/s",
            "mm^2/s",
            1e6,
            1e-7,
            1e-3,
            15.32e-6,
            "log",
        ),
        _p(
            "air_side.fluid.dynamic_viscosity",
            a,
            "Air μ",
            "Pa s",
            "mPa s",
            1e3,
            1e-6,
            1.0,
            18.21548e-6,
            "log",
        ),
        _p("air_side.fluid.prandtl", a, "Air Pr", "-", "-", 1.0, 0.1, 1000.0, 0.70834, "log"),
        _p(
            "air_side.value",
            a,
            "Air face velocity",
            "m/s",
            "m/s",
            1.0,
            0.1,
            50.0,
            5.0,
            "log",
            mode="constant_velocity",
        ),
        _p(
            "air_side.value",
            a,
            "Air volume flow",
            "m^3/s",
            "m^3/s",
            1.0,
            1e-3,
            10.0,
            5.0 * 0.0984 * 0.160,
            "log",
            mode="constant_volume_flow",
            description="Face velocity = V̇/(width·tube_length)",
        ),
        _p(
            "air_side.value",
            a,
            "Air mass flow",
            "kg/s",
            "kg/s",
            1.0,
            1e-3,
            10.0,
            5.0 * 0.0984 * 0.160 * 1.189,
            "log",
            mode="constant_mass_flow",
        ),
        # --- coolant side -----------------------------------------------------
        _p(
            "coolant_side.fluid.density",
            c,
            "Coolant density ρ",
            "kg/m^3",
            "kg/m^3",
            1.0,
            100.0,
            2000.0,
            1041.5,
            "log",
        ),
        _p(
            "coolant_side.fluid.specific_heat_capacity",
            c,
            "Coolant cp",
            "J/(kg K)",
            "J/(kg K)",
            1.0,
            100.0,
            10000.0,
            3555.0,
            "log",
        ),
        _p(
            "coolant_side.fluid.thermal_conductivity",
            c,
            "Coolant λ",
            "W/(m K)",
            "W/(m K)",
            1.0,
            0.05,
            2.0,
            0.423,
            "log",
        ),
        _p(
            "coolant_side.fluid.kinematic_viscosity",
            c,
            "Coolant ν",
            "m^2/s",
            "mm^2/s",
            1e6,
            1e-8,
            1e-3,
            1.23e-6,
            "log",
        ),
        _p(
            "coolant_side.fluid.dynamic_viscosity",
            c,
            "Coolant μ",
            "Pa s",
            "mPa s",
            1e3,
            1e-5,
            10.0,
            1.2825e-3,
            "log",
        ),
        _p(
            "coolant_side.fluid.prandtl",
            c,
            "Coolant Pr",
            "-",
            "-",
            1.0,
            0.1,
            1000.0,
            10.77846,
            "log",
        ),
        _p(
            "coolant_side.value",
            c,
            "Coolant tube velocity",
            "m/s",
            "m/s",
            1.0,
            0.01,
            5.0,
            0.5,
            "log",
            mode="constant_velocity",
        ),
        _p(
            "coolant_side.value",
            c,
            "Coolant volume flow",
            "m^3/s",
            "L/min",
            60000.0,
            1e-5,
            1e-2,
            2.7143e-4,
            "log",
            mode="constant_volume_flow",
            description="Total bundle flow; UI seed ≈ paper design point",
        ),
        _p(
            "coolant_side.value",
            c,
            "Coolant mass flow",
            "kg/s",
            "kg/s",
            1.0,
            1e-2,
            10.0,
            0.2827,
            "log",
            mode="constant_mass_flow",
        ),
        _p(
            "coolant_side.value",
            c,
            "Coolant pressure drop",
            "Pa",
            "bar",
            1e-5,
            1e3,
            5e5,
            1e4,
            "log",
            mode="constant_pressure_drop",
            description="Straight-tube friction Δp target (diagnostic model)",
        ),
        _p(
            "coolant_side.value",
            c,
            "Coolant hydraulic power",
            "W",
            "W",
            1.0,
            0.01,
            1000.0,
            3.0,
            "log",
            mode="constant_hydraulic_power",
        ),
        # --- boundary conditions and screens ---------------------------------
        _p(
            "boundary_conditions.wall_tolerance",
            b,
            "Wall tolerance Δt",
            "m",
            "mm",
            1e3,
            0.0,
            5e-5,
            0.020e-3,
            "linear",
            step_display=0.001,
            description="Lamé screen uses t_loc,min = t_nom − Δt",
        ),
        _p(
            "boundary_conditions.screens.min_burst_pressure",
            b,
            "Min burst pressure",
            "Pa",
            "bar",
            1e-5,
            0.0,
            2e6,
            6e5,
            "linear",
            step_display=0.1,
        ),
        _p(
            "boundary_conditions.screens.min_coolant_volume_flow",
            b,
            "Min coolant flow",
            "m^3/s",
            "L/min",
            60000.0,
            0.0,
            1e-3,
            10.0 / 60000.0,
            "linear",
            step_display=0.5,
        ),
        _p(
            "boundary_conditions.screens.max_tube_pressure_drop",
            b,
            "Max friction Δp",
            "Pa",
            "bar",
            1e-5,
            1e3,
            5e5,
            0.5e5,
            "log",
        ),
        _p(
            "boundary_conditions.screens.max_cost_index",
            b,
            "Max cost index",
            "-",
            "-",
            1.0,
            0.1,
            100.0,
            5.0,
            "log",
        ),
        _p(
            "boundary_conditions.screens.max_capillary_rise",
            b,
            "Max capillary rise",
            "m",
            "mm",
            1e3,
            1e-4,
            0.1,
            2e-3,
            "log",
        ),
        _p(
            "boundary_conditions.screens.capillary_acceleration_over_g",
            b,
            "Capillary acceleration factor G",
            "-",
            "-",
            1.0,
            1.0,
            20.0,
            10.0,
            "linear",
            step_display=1.0,
        ),
        # --- sweep (request-level) --------------------------------------------
        _p(
            "sweep.outer_diameter_min",
            "sweep",
            "Sweep d_o minimum",
            "m",
            "mm",
            1e3,
            0.01e-3,
            5e-3,
            0.1e-3,
            "log",
        ),
        _p(
            "sweep.outer_diameter_max",
            "sweep",
            "Sweep d_o maximum",
            "m",
            "mm",
            1e3,
            1e-3,
            50e-3,
            10e-3,
            "log",
        ),
        _p(
            "sweep.wall_thickness_min",
            "sweep",
            "Sweep wall t minimum",
            "m",
            "mm",
            1e3,
            0.0001e-3,
            0.1e-3,
            0.001e-3,
            "log",
        ),
        _p(
            "sweep.wall_thickness_max",
            "sweep",
            "Sweep wall t maximum",
            "m",
            "mm",
            1e3,
            0.1e-3,
            20e-3,
            4.5e-3,
            "log",
        ),
        _p(
            "sweep.n_outer_diameter",
            "sweep",
            "Grid points d_o",
            "-",
            "-",
            1.0,
            16,
            1000,
            250,
            "linear",
            step_display=1,
            integer=True,
        ),
        _p(
            "sweep.n_wall_thickness",
            "sweep",
            "Grid points wall t",
            "-",
            "-",
            1.0,
            16,
            1000,
            250,
            "linear",
            step_display=1,
            integer=True,
        ),
        _p(
            "sweep.wall_ratio_calc_max_pct",
            "sweep",
            "τ calculation window max",
            "%",
            "%",
            1.0,
            5.0,
            50.0,
            45.0,
            "linear",
            step_display=1.0,
        ),
    ]
